[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "SxT5E9r5ze"
weight = 9999

[[main]]
name = "Tasks"
pageRef = "newSite"
identifier = "uCOvHofVWp"
weight = 9999

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "newSite"
identifier = "MpllO5eKdy"
weight = 9999
