[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Parent"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 20

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "uSdHwMNIug"
weight = 9999

[[subnavigation]]
name = "An interesting topic"
pageRef = "tags/interesting-topic"
weight = 10

[[footer]]
none = "none"
