[[main]]
name = "Blog"
pageRef = "posts"
identifier = "uSdHwMNIug"
weight = 9999

[[subnavigation]]
name = "An interesting topic"
pageRef = "tags/interesting-topic"
weight = 10

[[footer]]
none = "none"
